apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
spec:
  minReadySeconds: 10
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
      - name: backstage
        image: ghcr.io/danielmunro/otto-backstage:v0.1.5
        imagePullPolicy: Always
        ports:
          - containerPort: 7007
            name: http
            protocol: TCP
        env:
#          - name: APP_CONFIG_app_baseUrl
#            value: https://backstage.thirdplaceapp.com
#          - name: APP_CONFIG_backend_baseUrl
#            value: http://backstage:7007
#          - name: APP_CONFIG_backend_cors_origin
#            value: https://backstage.thirdplaceapp.com
          - name: APP_CONFIG_backend_database_connection_host
            valueFrom:
              secretKeyRef:
                name: backstage
                key: postgres_host
          - name: APP_CONFIG_backend_database_connection_port
            valueFrom:
              secretKeyRef:
                name: backstage
                key: postgres_port
          - name: APP_CONFIG_backend_database_connection_user
            valueFrom:
              secretKeyRef:
                name: backstage
                key: postgres_user
          - name: APP_CONFIG_backend_database_connection_password
            valueFrom:
              secretKeyRef:
                name: backstage
                key: postgres_password
