apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage
spec:
  minReadySeconds: 10
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 60
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: backstage
  template:
    metadata:
      labels:
        app: backstage
    spec:
      containers:
      - name: otto-backstage
        image: ghcr.io/danielmunro/otto-backstage:v0.1.2
        imagePullPolicy: Always
        ports:
          - containerPort: 7007
            name: http
            protocol: TCP
