app:
  # Should be the same as backend.baseUrl when using the `app-backend` plugin
  baseUrl: http://backstage:7007

backend:
  baseUrl: http://backstage:7007
  listen:
    port: 7007
  database:
    client: pg
    connection:
      host: foo
      port: 123
      user: bar
      password: baz

catalog:
  readonly: true
