on:
  push:
    branches:
      - main
jobs:
  build-and-publish-docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - run: yarn install --frozen-lockfile
      - run: yarn tsc
      - run: yarn build
      - run: |
          echo $CR_PAT | docker login ghcr.io -u danielmunro --password-stdin
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
      - run: docker build . -f packages/backend/Dockerfile --tag ghcr.io/danielmunro/otto-backstage:latest
      - run: docker push ghcr.io/danielmunro/otto-backstage:latest
  deploy-to-lambda:
    runs-on: ubuntu-latest
    needs:
      - build-and-publish-docker
    steps:
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-west-2
          subnets: ${{ secrets.AWS_SUBNET }}
          function_name: otto-backstage
          image_uri: ghcr.io/danielmunro/otto-backstage:latest

